# Generated by Django 5.0.3 on 2024-03-07 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patient_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='medication',
            name='properties',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(related_name='patients_with_allergy', to='users.property'),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.AddField(
            model_name='medication',
            name='properties',
            field=models.ManyToManyField(to='users.property'),
        ),
    ]
