# Generated by Django 5.0.3 on 2024-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_medicationorder_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
