# Generated by Django 5.0.3 on 2024-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_medicationorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=10),
        ),
    ]
